site_name: "Open Strata Documentation"
theme:
  name: "material"  # You can use mkdocs-material for a similar theme
nav:
  - Home: index.md
  - About Open Strata:
      - Overview: overview.md
      - Getting Started: getting-started.md
      - Installation:
          - Quick Start: installation/quick-start.md
          - Using Helm: installation/helm.md
docs_dir: docs
site_dir: site